// <auto-generated />
using System;
using ATINV.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ATINV.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ATINV.Model.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<decimal>("MinInicialContribution")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Fund");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77c725c9-dc4f-49d0-ab59-d316cd500abe"),
                            Cnpj = "78092564000199",
                            MinInicialContribution = 1000m,
                            Name = "Fundo ABC"
                        },
                        new
                        {
                            Id = new Guid("e967dd84-d7b8-400f-988d-a645ec1adabd"),
                            Cnpj = "37165877000142",
                            MinInicialContribution = 5000m,
                            Name = "Fundo XYZ"
                        },
                        new
                        {
                            Id = new Guid("1eb19aa1-3097-4635-af32-be9de020947a"),
                            Cnpj = "10289932000150",
                            MinInicialContribution = 100000m,
                            Name = "Fundo XPTO"
                        });
                });

            modelBuilder.Entity("ATINV.Model.Moviment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<DateTime>("Date");

                    b.Property<Guid>("FundId");

                    b.Property<int>("MovimentType");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.ToTable("Moviment");
                });

            modelBuilder.Entity("ATINV.Model.Moviment", b =>
                {
                    b.HasOne("ATINV.Model.Fund", "Fund")
                        .WithMany("Moviments")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
